config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients
  has_many :directions
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
  validates :title, :description, :image, presence: true
  has_attached_file :image, styles: { medium: "400x400#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recipes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user, except: [:index, :show]
  def index
    @recipe = Recipe.all.order('created_at DESC')
  end

  def new
    @recipe = current_user.recipes.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: 'Successfully created new recipe'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: 'Successfully deleted recipe'
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy],
    directions_attributes: [:id, :step, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RecipeBox
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/shared/header'
    = render 'layouts/shared/messages'
    = yield

app/views/layouts/shared/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand= link_to "Recipe Box", root_path
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        %li= link_to "New Recipe", new_recipe_path
    - else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Sign Up", new_user_registration_path
        %li= link_to "Sign In", new_user_session_path

app/views/layouts/shared/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/recipes/_direction_fields.html.haml
.nested-fields
  .field
    = f.label :step
    = f.text_field :step
  = link_to_remove_association "remove task", f

app/views/recipes/_form.html.haml
= form_for @recipe do |f|
  - if @recipe.errors.any?
    %h2= pluralize(@recipe.errors.count, 'error')
    %ul
      - @recipe.errors.full_messages.each do |msg|
        %li= msg
  .content_form
    = f.label :title
    .input-group-lg
      = f.text_field :title, class: "form-control", placeholder: 'Titulo'
    = f.label :description
    .input-group-lg
      = f.text_area :description, class: "form-control", placeholder: 'Url'
    .input-group
      = f.file_field :image, input_html: { class: 'form-control' }
  .row
    .col-md-6
      %h3 Ingredients
      #ingredients
        .links
          = link_to_add_association 'Add Question', f, :ingredients, partial: 'ingredient_fields', class: "btn btn-default add-button"
    .col-md-6
      %h3 Directions
      #directions
        .links
          = link_to_add_association 'Add Direction', f, :directions, partial: 'direction_fields', class: "btn btn-default add-button"
      = f.submit

app/views/recipes/_ingredient_fields.html.haml
.nested-fields
  .field
    = f.label :name
    = f.text_field :name
  = link_to_remove_association "remove task", f

app/views/recipes/edit.html.haml
%h3 UPdate recipe
= render 'form'

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
  .row
    - recipes.each do |recipe|
      .col-md-4
        .recipe
          .image_wrapper
            = link_to recipe do
              = image_tag recipe.image.url(:medium)
          %h2= link_to recipe.title, recipe
= link_to 'New recipe', new_recipe_path

app/views/recipes/new.html.haml
%h2 new recipe
= render 'form'

app/views/recipes/show.html.haml
.main_content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium), class: "recipe_image"
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        %p.description= @recipe.description
        %p
          Submitted #{time_ago_in_words(@recipe.created_at)} by #{@recipe.user.email}
  .row
    .col-md-6
      #ingredients
        %h2 Ingredients
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li= ingredient.name

    .col-md-6
      #directions
        %h2 Directions
        %ul
          - @recipe.directions.each do |direction|
            %li= direction.step
  .row
    .col-md-12
      - if user_signed_in?
        = link_to "Edit", edit_recipe_path, class: "btn btn-default"
        = link_to "Delete", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>